import type { TServiceParams, TOffset } from "@digital-alchemy/core";
import type { PICK_ENTITY } from "@digital-alchemy/hass";

interface IMotionSwitchConfig {
  /**
   * Motion trigger will only activate if this switch is turned on
   */
  switchName: string;
  /**
   * Light controlled by motion sensor
   */
  lightId: PICK_ENTITY<"light">;

  /**
   * A binary sensor generated by a motion sensor
   */
  sensorId: PICK_ENTITY<"binary_sensor">;

  /**
   * If any of these switches are turned on, the motion sensor will *not* fire
   */
  blockSwitches?: PICK_ENTITY<"switch">[];

  /**
   * The time interval before a switch is turned off
   */
  timeout: TOffset;
}

/**
 * Create a motion sensor controlled light
 */
export function CreateMotionLightService({ synapse, context, scheduler, hass }: TServiceParams) {
  const create = ({
    switchName,
    sensorId,
    lightId,
    timeout,
    blockSwitches,
  }: IMotionSwitchConfig) => {
    const theSwitch = synapse.switch({
      name: switchName,
      context,
    });

    const theSensor = hass.refBy.id(sensorId);
    const theLight = hass.refBy.id(lightId);

    theSensor.onUpdate(async (_, newState) => {
      const anyBlockSwitchIsOn = blockSwitches
        ?.map(hass.refBy.id)
        .some((theSwitch) => theSwitch.state === "on");

      if (newState.state === "on" && theSwitch.is_on && !anyBlockSwitchIsOn) {
        await theLight.turn_on();
        scheduler.setTimeout(async () => {
          await theLight.turn_off();
        }, timeout);
      }
    });
  };

  return { create };
}
