import type { TServiceParams, TOffset } from "@digital-alchemy/core";
import type { PICK_ENTITY, RemoveCallback, TAreaId } from "@digital-alchemy/hass";

interface IMotionSwitchConfig {
  /**
   * Motion trigger will only activate if this switch is turned on
   */
  switchName: string;
  /**
   * Lights in this area are controllled by the motion sensor
   */
  area: TAreaId;

  /**
   * A binary sensor generated by a motion sensor
   */
  sensorId: PICK_ENTITY<"binary_sensor">;

  /**
   * If any of these switches are turned on, the motion sensor will *not* fire
   */
  blockSwitches?: PICK_ENTITY<"switch">[];

  /**
   * The time interval before a switch is turned off
   */
  timeout: TOffset;
}

/**
 * Create a motion sensor controlled light
 */
export function LightsService({
  synapse,
  context,
  scheduler,
  hass,
  logger,
  bens_flat,
}: TServiceParams) {
  const { helpers } = bens_flat;

  const turnOffAll = async () => {
    const lights = hass.refBy.domain(`light`);
    await helpers.turnOffAll(lights.map((entity) => entity.entity_id));
  };

  const setupMotionTrigger = ({
    switchName,
    sensorId,
    area,
    timeout,
    blockSwitches,
  }: IMotionSwitchConfig) => {
    const theSwitch = synapse.switch({
      name: switchName,
      unique_id: switchName.replace(/[^a-zA-Z0-9]/gi, ""),
      attributes: {
        area,
      },
      context,
    });

    let remove: RemoveCallback | undefined;

    const theSensor = hass.refBy.id(sensorId);

    theSensor.onUpdate(async (newState) => {
      logger.trace(`${sensorId} sensor triggered`);
      if (!newState) {
        return;
      }
      const anyBlockSwitchIsOn = blockSwitches
        ?.map(hass.refBy.id)
        .some((theSwitch) => theSwitch.state === "on");

      if (newState.state === "on" && theSwitch.is_on && !anyBlockSwitchIsOn) {
        logger.info(`Turning ${area} lights on`);
        remove?.remove();
        await hass.call.light.turn_on({ area_id: area });
        remove = scheduler.setTimeout(async () => {
          logger.info(`Turning ${area} lights off`);
          await hass.call.light.turn_off({ area_id: area });
        }, timeout);
      }
    });
  };

  return { setupMotionTrigger, turnOffAll };
}
